name: MineableSpawners
version: 1.5
main: net.momentonetwork.MineableSpawners
authors: [fergydanny]
description: A simplistic silk spawner plugin
website: https://momentonetwork.net
api-version: 1.13
commands:
  spawner:
    description: Change a spawners type. Usage /spawner (mob)
  spawnergive:
    description: Give a user a spawner. Usage /spawnergive (user) (mob) (amount)
